name: Python Tests

# Trigger the workflow on push or pull request events to the main branch
on:
  push:
    # triggers all branches
  pull_request:
    # triggers all branches

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # If using Pipenv, uncomment the next line
          # pip install pipenv && pipenv install --dev

      - name: Run Tests with pytest
        run: |
          pytest

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./test-results.xml
